# Project information
site_name: BSM2-Python
site_description: A Python implementation of the Benchmark Simulation Model 2 (BSM2) plant layout according to the IWA standard.
site_author: Jonas Miederer
site_url: https://bsm2-python-evt-klaeffizient-a1487fe7ab7d8b53e9093ea317383c33b8.pages.rrze.fau.de/
copyright: 'Copyright &copy; Jonas Miederer 2024-present'

# Repository
repo_name: bsm2-python
repo_url: https://gitlab.rrze.fau.de/evt/klaeffizient/bsm2-python
edit_uri: blob/master/docs

# Navigation
nav:
  - Home:
    - About: index.md
    - Changelog: changelog.md
    - License: license.md
    - Authors: authors.md
    - Contributing: contributing.md
    - Documentation: documentation.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/

# Configuration
docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  favicon: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/solid/egg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline # material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb # material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.tabs
#    - navigation.expand
    - navigation.tabs.sticky
    - navigation.instant

watch:
- src

# Extensions
plugins:
  # Built-in
  search: {}
  autorefs: {}
  social: {}
  # Extra
  include-markdown: {}
  glightbox: {}
  minify:
    minify_html: true
  mike:
    alias_type: copy
  gen-files:
    scripts:
      - docs/scripts/gen_ref_nav.py
  literate-nav:
    nav_file: SUMMARY.md
  section-index: {}
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
          - src
        options:            # https://mkdocstrings.github.io/python/usage/#options-summary
          # General
          show_bases: false
          # Headings
          heading_level: 1
          show_root_heading: true
          show_root_full_path: false
          show_root_toc_entry: true
          show_category_heading: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # Members
          show_submodules: no
          show_labels: false
          # Docstrings
          docstring_style: numpy
          docstring_section_style: table
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_if_no_docstring: false
          # Signatures/annotations
          separate_signature: true
          show_signature_annotations: false


markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: pypa
      repo: hatch
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/snippets
      auto_append:
        - links.txt
        # - abbrs.txt
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://gitlab.rrze.fau.de/evt/klaeffizient/bsm2-python
  #  - icon: fontawesome/solid/blog
  #    link: https://....
  #  - icon: fontawesome/brands/linkedin
  #    link: https://www.linkedin.com/in/xxxxxx/
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXX
