name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Code
        run: |
          git config --global --add safe.directory /__w/bsm2-python/bsm2-python
          hatch run lint:style

      # - name: Upload pre-commit log
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pre-commit-log
      #     path: /github/home/.cache/pre-commit/pre-commit.log
      #     if-no-files-found: warn

  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            run_tests:
              - 'src/**'
              - 'tests/**'
              - 'Dockerfile'
              - '.github/workflows/ci.yml'
      - name: Run Tests
        if: steps.filter.outputs.run_tests == 'true'
        run: |
          git config --global --add safe.directory /__w/bsm2-python/bsm2-python
          hatch run test:cov
