name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for pre-commit log
        id: precommitlog
        run: |
          if [ -f /github/home/.cache/pre-commit/pre-commit.log ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Lint Code
        run: |
          echo "Current working directory:"
          pwd
          ls -la
          hatch run lint:style

      - name: Upload pre-commit log
        if: steps.precommitlog.outputs.found == 'true' || failure()
        uses: actions/upload-artifact@v3
        with:
          name: pre-commit-log
          path: /github/home/.cache/pre-commit/pre-commit.log

  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Current working directory:"
          pwd
          ls -la
          hatch run test:cov
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/