name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Code
        run: |
          echo "Current working directory:"
          pwd
          hatch run lint:style

  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Current working directory:"
          pwd
          hatch run test:cov
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/